const asset = (name:string) => `${import.meta.env.BASE_URL}${name}`;



import { useEffect, useState } from "react";
import { ArrowUpRight, ArrowDown, ArrowRight, Pause, Play, X, LayoutDashboard, GitBranch as Github, BriefcaseBusiness as Linkedin, Mail, Code2, Database, CreditCard, Package, Sparkles } from "lucide-react";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "./accordion";

type Project = {
 id:string; n:string; name:string; category:string; title:string; text:string; stack:string[]; url:string; detail:string; decision:string; status:string; github?:boolean; image?:string; imageAlt?:string; modalNote?:string;
};
const projects:Project[] = [
  { id:"hexa", n:"03", name:"HexaClub", category:"COMÉRCIO / EXPERIÊNCIA MOBILE", title:"Escolher. Combinar. Pedir.", text:"Um catálogo que organiza a escolha do cliente antes da conversa com o vendedor.", stack:["JavaScript","CSS","WebP"], url:"https://hexaclub.com.br/", image:asset("hexaclub-site.png"), imageAlt:"Prévia da página inicial do HexaClub", modalNote:"Catálogo com seleção de tamanhos e cores, pedido estruturado e transição direta para o WhatsApp.", detail:"Desenvolvimento completo de catálogo com tamanhos e cores, lista de pedido, cupons e regra de brinde. A mensagem formatada leva os itens para o WhatsApp, onde acontece o fechamento.", decision:"Separei o HTML original em estrutura, estilos, configuração comercial e comportamento. A otimização documentada reduziu o peso das imagens de 62,6 MB para 5,6 MB — aproximadamente 91,1%.", status:"Site publicado · validação de cupons no navegador." },
  { id:"automation", n:"04", name:"Playwright Automation", category:"PYTHON / AUTOMAÇÃO", title:"Rotinas repetidas. Execução rastreável.", text:"Login, ação programada e evidências de execução em um ambiente demonstrativo local.", stack:["Python","Playwright","pytest"], url:"https://github.com/usamy175/playwright-scheduled-automation", detail:"Uma aplicação local simula autenticação e uma ação recorrente. A automação usa seletores estáveis, aguarda a confirmação visual, registra logs e captura a tela quando ocorre uma falha.", decision:"Separei aplicação, configuração, automação, agendamento e CLI. Os testes documentados cobrem configuração e o fluxo da aplicação local; testes end-to-end do robô são uma evolução prevista.", status:"Código público · demonstração local.", github:true },
  { id:"kyndro", n:"05", name:"Kyndro", category:"AGÊNCIA / IDENTIDADE DIGITAL", title:"Experiência que ganhou um nome.", text:"A presença digital da agência que cofundei com um colega, reunindo serviços e trabalhos realizados.", stack:["HTML & CSS","JavaScript","React"], url:"https://kyndro.com.br/", image:asset("kyndro-site.png"), imageAlt:"Prévia da página inicial da Kyndro", modalNote:"Site institucional da agência, com identidade própria, serviços e portfólio reunidos em uma narrativa única.", detail:"Fui responsável pelo desenvolvimento completo do site: identidade aplicada, portfólio filtrável, detalhes dos projetos e adaptações para mobile. A criação da agência é uma parceria.", decision:"Mantive a interface estática portátil dentro do ambiente React. O site usa prévias reais dos projetos, navegação por âncoras e animações que respeitam movimento reduzido.", status:"Site publicado · contatos diretos; formulário demonstrativo." },
  { id:"silva", n:"06", name:"Silva & Campos", category:"INSTITUCIONAL / ADVOCACIA", title:"Clareza que aproxima pessoas.", text:"Identidade, especialidades e profissionais organizados em uma jornada direta até o atendimento.", stack:["React","TypeScript","PowerShell"], url:"https://silvaecamposadvocacia.com.br/", image:asset("silvaecampos-site.png"), imageAlt:"Prévia da página inicial da Silva & Campos Advocacia", modalNote:"Presença institucional com áreas de atuação, perfis dos profissionais e caminhos de contato contextualizados.", detail:"Desenvolvimento completo de site responsivo com seis áreas de atuação, perfis expansíveis, contatos contextualizados e mapa. A interface traduz a identidade visual fornecida pelo escritório.", decision:"Criei uma exportação estática a partir da aplicação React para funcionar na hospedagem compartilhada do cliente. O pacote inclui HTML, CSS, recursos e JavaScript das interações.", status:"Site publicado · avaliações selecionadas manualmente." }
];
const stages = [
 { name:"Simulação", tech:"Python · Utility AI", text:"Necessidades, personalidade e relações influenciam as decisões de dez moradores. O backend mantém o estado do mundo." },
 { name:"Eventos", tech:"Scoring determinístico", text:"Acontecimentos recebem uma pontuação de relevância. Mudanças importantes são conectadas em sequências de eventos." },
 { name:"Direção", tech:"Director · Phaser", text:"O Director escolhe o foco da câmera e destaca os participantes. A apresentação observa os fatos sem alterar a simulação." },
 { name:"Captura", tech:"Canvas · MediaRecorder", text:"O navegador captura o canvas real com os momentos anteriores e posteriores ao evento, junto de metadados estruturados." },
 { name:"Vídeo", tech:"FFmpeg · MP4 vertical", text:"O processamento local compõe vídeos verticais com enquadramento e texto factual. A revisão e a publicação são manuais." }
];
const phelpProject:Project = { id:"phelp", n:"02", name:"Phelp Club", category:"E-COMMERCE FULL STACK", title:"Uma loja. Toda a operação.", text:"Vitrine, pedidos, pagamentos e expedição em uma aplicação construída para a rotina de uma marca de moda.", stack:["Node.js","Express","MySQL","JavaScript"], url:"https://phelpclub.com.br/", image:asset("phelpclub-site.png"), imageAlt:"Prévia da loja online Phelp Club", modalNote:"Loja pública conectada a uma operação administrativa para produtos, estoque, pedidos, pagamentos e expedição.", detail:"Dar autonomia ao lojista para administrar produtos, variações, estoque e pedidos, conectando cobrança, frete e comunicação com o comprador.", decision:"Desenvolvimento completo, com apoio de IA e evolução a partir do feedback do cliente. Monolito modular, conciliação de pagamentos, OAuth de logística e imagens preservadas no banco entre publicações.", status:"Loja e API publicadas na Hostinger com MySQL." };

const aquariumProject:Project = { id:"aquarium", n:"01", name:"AI Aquarium", category:"SISTEMAS MULTIAGENTE", title:"Pequenas decisões. Histórias que emergem.", text:"Dez moradores autônomos em um mundo persistente.", stack:["Python","FastAPI","React","TypeScript","Phaser","FFmpeg"], url:"", image:asset("aquarium-cover.png"), imageAlt:"Ilustração do AI Aquarium com moradores, casas, comércio e um lago central", modalNote:"Um mundo de necessidades, relações e decisões autônomas. Ilustração de apresentação do projeto.", detail:"Construir uma sociedade simulada na qual necessidades, personalidade e relações influenciam as decisões de dez moradores.", decision:"Utility AI explicável, determinismo por seed e persistência em SQLite. A observação, a câmera e a captura não alteram a simulação.", status:"Projeto local em evolução. Revisão e publicação dos vídeos são manuais." };

function PhelpDashboardPreview() {
 return <div className="dashboard-preview" aria-label="Demonstração visual do dashboard administrativo da Phelp Club">
  <div className="dashboard-topbar"><span className="dashboard-mark">PHELP / ADMIN</span><span className="dashboard-user">JG · operador</span></div>
  <div className="dashboard-body"><aside><span className="dashboard-nav active">Visão geral</span><span className="dashboard-nav">Pedidos</span><span className="dashboard-nav">Produtos</span><span className="dashboard-nav">Estoque</span></aside><div className="dashboard-content"><div className="dashboard-heading"><div><small>PAINEL ADMINISTRATIVO</small><strong>Visão geral</strong></div><span className="dashboard-date">Hoje · 09:42</span></div><div className="dashboard-metrics"><div><small>Vendas no mês</small><strong>R$ 18.420</strong><span className="metric-up">+12,8%</span></div><div><small>Pedidos abertos</small><strong>28</strong><span>7 aguardando envio</span></div><div><small>Ticket médio</small><strong>R$ 263</strong><span>últimos 30 dias</span></div></div><div className="dashboard-lower"><div className="dashboard-chart"><div className="chart-label"><small>VENDAS POR DIA</small><span>↑ 18%</span></div><div className="chart-bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="dashboard-orders"><small>ÚLTIMOS PEDIDOS</small><span><b>#1048</b><em>Separação</em></span><span><b>#1047</b><em className="shipped">Enviado</em></span><span><b>#1046</b><em>Pagamento</em></span></div></div></div></div>
 </div>;
}

function ProjectPreview({project,onOpen}:{project:Project;onOpen:(project:Project)=>void}) {
 return <button type="button" className={`project-preview ${project.image?"has-image":"is-placeholder"} ${project.id}`} onClick={()=>onOpen(project)} aria-label={`Abrir detalhes visuais de ${project.name}`}>
  {project.image ? <img src={project.image} alt={project.imageAlt || `Prévia de ${project.name}`} /> : <div className="preview-placeholder"><span className="preview-placeholder-kicker">DEMONSTRAÇÃO LOCAL</span><strong>{project.name}</strong><span className="preview-code">{project.stack.join(" · ")}</span><div className="preview-code-lines"><i/><i/><i/><i/></div></div>}
  <span className="preview-open">Ver estudo <ArrowUpRight size={16}/></span>
 </button>;
}

function ProjectModal({project,onClose}:{project:Project;onClose:()=>void}) {
 useEffect(()=>{const closeOnEscape=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};document.addEventListener("keydown",closeOnEscape);const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",closeOnEscape);document.body.style.overflow=previous}},[onClose]);
 return <div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><div className={`project-modal-card ${project.id}`}><button type="button" className="modal-close" onClick={onClose} aria-label="Fechar detalhes"><X size={20}/></button><div className="modal-copy"><p className="eyebrow">{project.n} / {project.category}</p><h2 id="project-modal-title">{project.name}</h2><p className="modal-lead">{project.title}</p><p>{project.modalNote || project.text}</p><Tags items={project.stack}/><div className="modal-actions">{project.url && <External href={project.url} className="text-link">{project.github?"Ver código demonstrativo":"Visitar projeto"}</External>}<button type="button" className="modal-secondary" onClick={onClose}>Voltar aos projetos</button></div></div><div className="modal-visual">{project.id==="phelp" ? <><ProjectPreview project={project} onOpen={()=>{}}/><div className="dashboard-heading-label"><LayoutDashboard size={17}/> Também construí a operação administrativa</div><PhelpDashboardPreview/></> : <ProjectPreview project={project} onOpen={()=>{}}/>}</div><div className="modal-detail"><div><h4>O desafio</h4><p>{project.detail}</p></div><div><h4>Decisão técnica</h4><p>{project.decision}</p></div><div><h4>Estado da entrega</h4><p>{project.status}</p></div></div></div></div>;
}
function External({href,children,className=""}:{href:string;children:React.ReactNode;className?:string}) {
 return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={18}/></a>;
}
function Tags({items}:{items:string[]}) {return <div className="tags">{items.map(t=><span key={t}>{t}</span>)}</div>}
function Detail({id,children}:{id:string;children:React.ReactNode}) {
 return <Accordion><AccordionItem value={id} className="case-accordion"><AccordionTrigger className="case-trigger">Explorar detalhes do projeto</AccordionTrigger><AccordionContent className="case-content">{children}</AccordionContent></AccordionItem></Accordion>;
}
export default function Home() {
 const [paused,setPaused]=useState(false);
 const [reduced,setReduced]=useState(false);
 const [stage,setStage]=useState(0);
 const [selectedProject,setSelectedProject]=useState<Project|null>(null);
 useEffect(()=>{const m=window.matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>setReduced(m.matches);sync();m.addEventListener("change",sync);return()=>m.removeEventListener("change",sync)},[]);
 useEffect(()=>{if(paused||reduced)return;const id=window.setInterval(()=>setStage(s=>(s+1)%stages.length),4200);return()=>clearInterval(id)},[paused,reduced]);
 useEffect(()=>{if(reduced||paused)return;const items=document.querySelectorAll(".reveal");const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("seen");obs.unobserve(e.target)}}),{threshold:.08});items.forEach(e=>{e.classList.add("reveal-ready");obs.observe(e)});return()=>{obs.disconnect();items.forEach(e=>e.classList.remove("reveal-ready"))}},[reduced,paused]);
 useEffect(()=>{let raf=0;const update=()=>{if(raf)return;raf=window.requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-window.innerHeight;const progress=max>0?window.scrollY/max:0;document.documentElement.style.setProperty("--scroll-progress",progress.toFixed(4));document.documentElement.style.setProperty("--scroll-y",`${window.scrollY}px`);raf=0})};update();window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{window.removeEventListener("scroll",update);window.removeEventListener("resize",update);if(raf)window.cancelAnimationFrame(raf)}},[]);
 return <div className={paused||reduced?"portfolio motion-paused":"portfolio"}>
  <div className="scroll-progress" aria-hidden="true" />
  <a className="skip-link" href="#projetos">Pular para os projetos</a>
  <header className="nav"><a className="brand" href="#inicio" aria-label="Julio Guilherme, início"><img className="brand-avatar" src={asset("julio-avatar.png")} alt=""/><span className="brand-initials">JG<span>↗</span></span></a><nav aria-label="Navegação principal"><a href="#sobre">Sobre mim</a><a href="#projetos">Projetos</a><a href="#contato">Contato <ArrowUpRight size={15}/></a></nav><button className="motion-control" onClick={()=>setPaused(p=>!p)} aria-label={paused?"Retomar animações":"Pausar animações"} aria-pressed={paused} disabled={reduced} title={reduced?"Movimento reduzido pelo dispositivo":paused?"Retomar animações":"Pausar animações"}>{paused||reduced?<Play size={15}/>:<Pause size={15}/>}<span>{reduced?"Movimento reduzido":paused?"Retomar":"Pausar movimento"}</span></button></header>
  <main id="inicio">
   <section id="sobre" className="about-section"><div className="wrap about-grid"><div className="about-identity reveal"><p className="eyebrow">01 / SOBRE MIM</p><div className="portrait-stack"><figure className="portrait avatar-portrait"><img src={asset("julio-avatar-crossed-arms.png")} alt="Avatar 3D de Julio Guilherme, com cabelos cacheados, óculos e braços cruzados"/></figure></div><h1>Julio Guilherme<span>Desenvolvimento de Software, Automação e IA.</span></h1><div className="about-actions"><a href="#aquarium" className="about-primary">Ver meus projetos <ArrowDown size={18}/></a><External href="https://github.com/usamy175" className="text-link"><Github size={18}/>GitHub</External><a className="text-link" href="mailto:juliogui.dias@gmail.com">Contato <ArrowUpRight size={18}/></a><External href="https://linkedin.com/in/julioguilhermedias" className="text-link"><Linkedin size={18}/>LinkedIn</External></div></div><div className="about-copy reveal"><p className="about-lead">Sou Julio Guilherme, estudante de Análise e Desenvolvimento de Sistemas na Fatec Taubaté, com conclusão prevista para julho de 2027.</p><p>Desenvolvo projetos de software, automação e inteligência artificial utilizando tecnologias como Python, TypeScript, FastAPI, React, SQL e Playwright. Entre meus trabalhos estão aplicações web comerciais e uma simulação full stack de agentes autônomos, com comportamentos, economia, relações sociais e tomada de decisões por Utility AI.</p><p>Utilizo inteligência artificial como ferramenta para acelerar pesquisa, implementação e testes, mantendo responsabilidade pelas decisões técnicas, validação e qualidade de cada entrega. Também cofundei a Kyndro, agência de desenvolvimento web.</p><div className="research"><Sparkles size={21}/><div><h4>Da prática à pesquisa</h4><p>Sou bolsista de iniciação científica no INPE/CNPq, desenvolvendo uma pesquisa computacional sobre otimização de absorvedores eletromagnéticos multicamadas. O trabalho envolve modelagem analítica, tratamento de dados experimentais e desenvolvimento de algoritmos em Python com NumPy e Matplotlib.</p></div></div></div></div></section>
   <section id="projetos" className="wrap section">
    <div className="section-heading reveal"><div><p className="eyebrow">02 / TRABALHOS SELECIONADOS</p><h2>Construir. Entender.<br/>Ir além da interface.</h2></div><p className="section-intro">Seis projetos. Diferentes problemas.<br/>Decisões que conectam código e uso real.</p></div>
    <article id="aquarium" className="featured aquarium reveal">
     <div className="project-heading"><span className="eyebrow">01 / SISTEMAS MULTIAGENTE</span><span className="project-status"><i/>EM EVOLUÇÃO</span></div>
     <div className="aquarium-title"><div><h3>AI Aquarium</h3><p className="feature-lead">Pequenas decisões.<br/>Histórias que emergem.</p><p className="aquarium-description">Dez moradores autônomos. Um mundo persistente. Uma cadeia de observação que transforma acontecimentos em vídeos.</p></div><div className="aquarium-cover"><ProjectPreview project={aquariumProject} onOpen={setSelectedProject}/></div></div>
     <div className="aquarium-bottom"><Tags items={["Python","FastAPI","React","TypeScript","Phaser","FFmpeg"]}/><p><strong>264</strong> testes documentados <span>· milestone 5C4</span></p></div>
     <Detail id="aquarium">     <div className="pipeline" aria-label="Etapas da arquitetura do AI Aquarium">{stages.map((s,i)=><button key={s.name} className={stage===i?"pipeline-step active":"pipeline-step"} onClick={()=>{setStage(i);setPaused(true)}} aria-pressed={stage===i}><span className="step-number">0{i+1}</span><span>{s.name}</span><ArrowRight size={17}/></button>)}</div>
     <div className="pipeline-explanation"><span className="pipeline-tech">{stages[stage].tech}</span><p>{stages[stage].text}</p></div>
<div className="detail-columns"><div><h4>Coerência do mundo</h4><p>Utility AI explicável, determinismo por seed e persistência em SQLite. Necessidades, economia e relações competem pelo tempo dos agentes.</p></div><div><h4>Observar sem interferir</h4><p>Scoring, câmera e captura não alteram o estado da sociedade. O canvas é gravado e processado localmente pelo FFmpeg em vídeos verticais.</p></div><div><h4>Validação e escopo</h4><p>O README registra 213 testes de backend, 51 de frontend e simulações de até 100 dias. Sem LLM no ciclo de decisão. Revisão e publicação de vídeos são manuais; o fluxo atual é local e supervisionado.</p></div></div></Detail>
    </article>
    <article className="featured phelp reveal">
     <div className="project-heading"><span className="eyebrow">02 / E-COMMERCE FULL STACK</span><span className="project-status"><i/>SITE PUBLICADO</span></div>
     <div className="feature-main"><div><h3>Phelp Club</h3><p className="feature-lead">Uma loja. Toda a operação.</p><p>Vitrine, pedidos, pagamentos e expedição em uma aplicação construída para a rotina de uma marca de moda.</p><Tags items={["Node.js","Express","MySQL","JavaScript"]}/><External href="https://phelpclub.com.br/" className="text-link">Visitar projeto</External></div>
      <div className="phelp-visual"><ProjectPreview project={phelpProject} onOpen={setSelectedProject}/></div>
     </div>
     <Detail id="phelp"><div className="commerce-diagram" aria-label="Arquitetura resumida: loja e painel conectados à API Express, MySQL, InfinitePay e Melhor Envio"><div className="diagram-label">DA INTERFACE À OPERAÇÃO</div><div className="diagram-top"><span><Code2/>Loja</span><span><Package/>Painel</span></div><div className="connector"><span/></div><div className="api-node"><span className="node-dot"/>API EXPRESS <span className="node-sub">regras de negócio</span></div><div className="connector"><span/></div><div className="diagram-bottom"><span><Database/>MySQL</span><span><CreditCard/>InfinitePay</span><span><Package/>Melhor Envio</span></div><p className="diagram-caption">Uma publicação. Responsabilidades separadas.</p></div><div className="detail-columns"><div><h4>O desafio</h4><p>Dar autonomia ao lojista para administrar produtos, variações, estoque e pedidos, conectando cobrança, frete e comunicação com o comprador.</p></div><div><h4>Minha contribuição</h4><p>Desenvolvimento completo, com apoio de IA e evolução a partir do feedback do cliente. Monolito modular, conciliação de pagamentos, OAuth de logística e imagens preservadas no banco entre publicações.</p></div><div><h4>Estado da entrega</h4><p>Loja e API publicadas na Hostinger com MySQL. A evolução local de notificações PWA foi testada com transporte simulado e ainda precisa de validação em aparelho real.</p></div></div></Detail>
    </article>
    <div className="project-grid">{projects.map(p=><article className={"project-card reveal "+p.id} key={p.id}><div className="project-heading"><span className="project-number">{p.n}</span><span className="eyebrow">{p.category}</span></div><ProjectPreview project={p} onOpen={setSelectedProject}/><h3>{p.name}</h3><p className="project-tagline">{p.title}</p><p className="project-description">{p.text}</p><Tags items={p.stack}/><div className="card-link"><External href={p.url} className="text-link">{p.github?"Ver código demonstrativo":"Visitar projeto"}</External></div><Detail id={p.id}><h4>Construção</h4><p>{p.detail}</p><h4>Decisão técnica</h4><p>{p.decision}</p><p className="detail-status">{p.status}</p></Detail></article>)}</div>
   </section>

   <section className="wrap section skills-section"><div className="section-heading reveal"><div><p className="eyebrow">03 / FERRAMENTAS & RACIOCÍNIO</p><h2>A tecnologia vem<br/>com um propósito.</h2></div></div><div className="skill-list">{[{n:"01",title:"Interfaces que fazem sentido",text:"React · TypeScript · JavaScript · HTML · CSS",desc:"Navegação, responsividade e conteúdo alinhados à tarefa de quem usa."},{n:"02",title:"Sistemas que sustentam a experiência",text:"Python · FastAPI · Node.js · Express · SQL",desc:"Regras de negócio, APIs, integrações e persistência organizadas."},{n:"03",title:"Comportamento que pode ser explicado",text:"Playwright · pytest · Utility AI · WebSocket",desc:"Automação, testes e decisões de agentes com evidências observáveis."}].map(s=><div className="skill-row reveal" key={s.n}><span className="eyebrow">{s.n}</span><div><h3>{s.title}</h3><p>{s.desc}</p></div><span className="skill-tech">{s.text}</span></div>)}</div></section>
   <section id="contato" className="contact-section"><div className="wrap reveal"><img className="contact-photo" src={asset("julio-photo.jpg")} alt="Julio Guilherme em uma área externa usando uniforme técnico" width="180" height="180" loading="lazy"/><p className="eyebrow">04 / PRÓXIMA CONVERSA</p><a className="contact-title" href="mailto:juliogui.dias@gmail.com">Vamos construir<br/>algo juntos?<ArrowUpRight aria-hidden="true"/></a><div className="contact-bottom"><a href="mailto:juliogui.dias@gmail.com"><Mail size={19}/>juliogui.dias@gmail.com</a><div><External href="https://linkedin.com/in/julioguilhermedias"><Linkedin size={18}/>LinkedIn</External><External href="https://github.com/usamy175"><Github size={18}/>GitHub</External></div></div></div></section>
  </main>
  <footer className="wrap footer"><a className="brand" href="#inicio" aria-label="Voltar ao início"><img className="brand-avatar" src={asset("julio-avatar.png")} alt=""/><span className="brand-initials">JG<span>↗</span></span></a><span>© 2026 Julio Guilherme</span><a href="#inicio">Voltar ao topo ↑</a></footer>
  {selectedProject && <ProjectModal project={selectedProject} onClose={()=>setSelectedProject(null)}/>} 
 </div>;
}







